-- =============================================================================
-- 2025年名额分配到区招生计划数据
-- =============================================================================
-- Generated: 2026-02-12 23:23:11
-- Source: 2025年名额分配到区招生计划.csv

-- Delete existing 2025 data
DELETE FROM ref_quota_allocation_district WHERE year = 2025;

-- Insert 2025 quota allocation to district data
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042032' AND data_year = 2025), '042032', (SELECT id FROM ref_district WHERE code = 'SH'), 286, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042032' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '102056' AND data_year = 2025), '102056', (SELECT id FROM ref_district WHERE code = 'SH'), 319, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '102056' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '102057' AND data_year = 2025), '102057', (SELECT id FROM ref_district WHERE code = 'SH'), 255, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '102057' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152003' AND data_year = 2025), '152003', (SELECT id FROM ref_district WHERE code = 'SH'), 280, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152003' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152006' AND data_year = 2025), '152006', (SELECT id FROM ref_district WHERE code = 'SH'), 187, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152006' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '155001' AND data_year = 2025), '155001', (SELECT id FROM ref_district WHERE code = 'SH'), 52, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '155001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012001' AND data_year = 2025), '012001', (SELECT id FROM ref_district WHERE code = 'HP'), 126, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012003' AND data_year = 2025), '012003', (SELECT id FROM ref_district WHERE code = 'HP'), 136, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012003' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012005' AND data_year = 2025), '012005', (SELECT id FROM ref_district WHERE code = 'HP'), 59, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012005' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012007' AND data_year = 2025), '012007', (SELECT id FROM ref_district WHERE code = 'HP'), 96, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012007' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012008' AND data_year = 2025), '012008', (SELECT id FROM ref_district WHERE code = 'HP'), 86, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012008' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012009' AND data_year = 2025), '012009', (SELECT id FROM ref_district WHERE code = 'HP'), 76, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012009' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012010' AND data_year = 2025), '012010', (SELECT id FROM ref_district WHERE code = 'HP'), 96, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012010' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012002' AND data_year = 2025), '012002', (SELECT id FROM ref_district WHERE code = 'HP'), 40, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012006' AND data_year = 2025), '012006', (SELECT id FROM ref_district WHERE code = 'HP'), 38, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012006' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042001' AND data_year = 2025), '042001', (SELECT id FROM ref_district WHERE code = 'XH'), 52, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042008' AND data_year = 2025), '042008', (SELECT id FROM ref_district WHERE code = 'XH'), 90, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042008' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042035' AND data_year = 2025), '042035', (SELECT id FROM ref_district WHERE code = 'XH'), 89, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042035' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '043015' AND data_year = 2025), '043015', (SELECT id FROM ref_district WHERE code = 'XH'), 78, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '043015' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042002' AND data_year = 2025), '042002', (SELECT id FROM ref_district WHERE code = 'XH'), 53, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042036' AND data_year = 2025), '042036', (SELECT id FROM ref_district WHERE code = 'XH'), 31, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042036' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '052001' AND data_year = 2025), '052001', (SELECT id FROM ref_district WHERE code = 'CN'), 51, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '052001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CN') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '052002' AND data_year = 2025), '052002', (SELECT id FROM ref_district WHERE code = 'CN'), 72, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '052002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CN') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '053004' AND data_year = 2025), '053004', (SELECT id FROM ref_district WHERE code = 'CN'), 53, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '053004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CN') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062001' AND data_year = 2025), '062001', (SELECT id FROM ref_district WHERE code = 'JA'), 70, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062002' AND data_year = 2025), '062002', (SELECT id FROM ref_district WHERE code = 'JA'), 67, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062003' AND data_year = 2025), '062003', (SELECT id FROM ref_district WHERE code = 'JA'), 67, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062003' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062004' AND data_year = 2025), '062004', (SELECT id FROM ref_district WHERE code = 'JA'), 74, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062011' AND data_year = 2025), '062011', (SELECT id FROM ref_district WHERE code = 'JA'), 53, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062011' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '063004' AND data_year = 2025), '063004', (SELECT id FROM ref_district WHERE code = 'JA'), 53, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '063004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '064001' AND data_year = 2025), '064001', (SELECT id FROM ref_district WHERE code = 'JA'), 44, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '064001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '072001' AND data_year = 2025), '072001', (SELECT id FROM ref_district WHERE code = 'PT'), 84, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '072001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PT') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '072002' AND data_year = 2025), '072002', (SELECT id FROM ref_district WHERE code = 'PT'), 82, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '072002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PT') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '073003' AND data_year = 2025), '073003', (SELECT id FROM ref_district WHERE code = 'PT'), 84, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '073003' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PT') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '073082' AND data_year = 2025), '073082', (SELECT id FROM ref_district WHERE code = 'PT'), 30, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '073082' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PT') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '092001' AND data_year = 2025), '092001', (SELECT id FROM ref_district WHERE code = 'HK'), 76, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '092001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HK') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '092002' AND data_year = 2025), '092002', (SELECT id FROM ref_district WHERE code = 'HK'), 71, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '092002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HK') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '093001' AND data_year = 2025), '093001', (SELECT id FROM ref_district WHERE code = 'HK'), 56, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '093001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HK') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '102004' AND data_year = 2025), '102004', (SELECT id FROM ref_district WHERE code = 'YP'), 100, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '102004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'YP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '102032' AND data_year = 2025), '102032', (SELECT id FROM ref_district WHERE code = 'YP'), 100, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '102032' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'YP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '103002' AND data_year = 2025), '103002', (SELECT id FROM ref_district WHERE code = 'YP'), 84, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '103002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'YP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '122001' AND data_year = 2025), '122001', (SELECT id FROM ref_district WHERE code = 'MH'), 120, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '122001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '123001' AND data_year = 2025), '123001', (SELECT id FROM ref_district WHERE code = 'MH'), 120, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '123001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '122002' AND data_year = 2025), '122002', (SELECT id FROM ref_district WHERE code = 'MH'), 69, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '122002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '122003' AND data_year = 2025), '122003', (SELECT id FROM ref_district WHERE code = 'MH'), 86, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '122003' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '122004' AND data_year = 2025), '122004', (SELECT id FROM ref_district WHERE code = 'MH'), 69, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '122004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '132001' AND data_year = 2025), '132001', (SELECT id FROM ref_district WHERE code = 'BS'), 101, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '132001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '132002' AND data_year = 2025), '132002', (SELECT id FROM ref_district WHERE code = 'BS'), 101, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '132002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '133001' AND data_year = 2025), '133001', (SELECT id FROM ref_district WHERE code = 'BS'), 98, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '133001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '132003' AND data_year = 2025), '132003', (SELECT id FROM ref_district WHERE code = 'BS'), 34, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '132003' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '133003' AND data_year = 2025), '133003', (SELECT id FROM ref_district WHERE code = 'BS'), 49, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '133003' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '142001' AND data_year = 2025), '142001', (SELECT id FROM ref_district WHERE code = 'JD'), 87, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '142001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '142002' AND data_year = 2025), '142002', (SELECT id FROM ref_district WHERE code = 'JD'), 105, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '142002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '142004' AND data_year = 2025), '142004', (SELECT id FROM ref_district WHERE code = 'JD'), 35, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '142004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152001' AND data_year = 2025), '152001', (SELECT id FROM ref_district WHERE code = 'PD'), 109, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152002' AND data_year = 2025), '152002', (SELECT id FROM ref_district WHERE code = 'PD'), 109, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152004' AND data_year = 2025), '152004', (SELECT id FROM ref_district WHERE code = 'PD'), 140, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '153001' AND data_year = 2025), '153001', (SELECT id FROM ref_district WHERE code = 'PD'), 109, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '153001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '153004' AND data_year = 2025), '153004', (SELECT id FROM ref_district WHERE code = 'PD'), 94, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '153004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '153005' AND data_year = 2025), '153005', (SELECT id FROM ref_district WHERE code = 'PD'), 94, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '153005' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '151078' AND data_year = 2025), '151078', (SELECT id FROM ref_district WHERE code = 'PD'), 94, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '151078' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152005' AND data_year = 2025), '152005', (SELECT id FROM ref_district WHERE code = 'PD'), 56, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152005' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '162000' AND data_year = 2025), '162000', (SELECT id FROM ref_district WHERE code = 'JS'), 78, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '162000' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '163002' AND data_year = 2025), '163002', (SELECT id FROM ref_district WHERE code = 'JS'), 78, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '163002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '172001' AND data_year = 2025), '172001', (SELECT id FROM ref_district WHERE code = 'SJ'), 82, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '172001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '173001' AND data_year = 2025), '173001', (SELECT id FROM ref_district WHERE code = 'SJ'), 82, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '173001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '172002' AND data_year = 2025), '172002', (SELECT id FROM ref_district WHERE code = 'SJ'), 33, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '172002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '172004' AND data_year = 2025), '172004', (SELECT id FROM ref_district WHERE code = 'SJ'), 18, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '172004' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '174003' AND data_year = 2025), '174003', (SELECT id FROM ref_district WHERE code = 'SJ'), 82, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '174003' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '182001' AND data_year = 2025), '182001', (SELECT id FROM ref_district WHERE code = 'QP'), 112, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '182001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'QP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '183002' AND data_year = 2025), '183002', (SELECT id FROM ref_district WHERE code = 'QP'), 112, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '183002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'QP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '182002' AND data_year = 2025), '182002', (SELECT id FROM ref_district WHERE code = 'QP'), 49, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '182002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'QP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '202001' AND data_year = 2025), '202001', (SELECT id FROM ref_district WHERE code = 'FX'), 87, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '202001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'FX') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '202002' AND data_year = 2025), '202002', (SELECT id FROM ref_district WHERE code = 'FX'), 43, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '202002' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'FX') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '512000' AND data_year = 2025), '512000', (SELECT id FROM ref_district WHERE code = 'CM'), 62, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '512000' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CM') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, data_year, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '512001' AND data_year = 2025), '512001', (SELECT id FROM ref_district WHERE code = 'CM'), 31, 2025, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '512001' AND data_year = 2025) AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CM') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;

-- Verify insert - show quota by school
SELECT s.code, s.full_name, d.code as district_code, qad.quota_count
FROM ref_quota_allocation_district qad
JOIN ref_school s ON qad.school_code = s.code AND s.data_year = 2025
JOIN ref_district d ON qad.district_id = d.id
WHERE qad.year = 2025
ORDER BY s.code, d.code;