-- =============================================================================
-- 2025年名额分配到区招生计划数据
-- =============================================================================
-- Generated: 2026-02-12 23:23:11
-- Source: 2025年名额分配到区招生计划.csv

-- Delete existing 2025 data
DELETE FROM ref_quota_allocation_district WHERE year = 2025;

-- Insert 2025 quota allocation to district data
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042032'), '042032', (SELECT id FROM ref_district WHERE code = 'SH'), 286, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042032') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '102056'), '102056', (SELECT id FROM ref_district WHERE code = 'SH'), 319, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '102056') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '102057'), '102057', (SELECT id FROM ref_district WHERE code = 'SH'), 255, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '102057') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152003'), '152003', (SELECT id FROM ref_district WHERE code = 'SH'), 280, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152003') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152006'), '152006', (SELECT id FROM ref_district WHERE code = 'SH'), 187, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152006') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '155001'), '155001', (SELECT id FROM ref_district WHERE code = 'SH'), 52, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '155001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012001'), '012001', (SELECT id FROM ref_district WHERE code = 'HP'), 126, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012003'), '012003', (SELECT id FROM ref_district WHERE code = 'HP'), 136, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012003') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012005'), '012005', (SELECT id FROM ref_district WHERE code = 'HP'), 59, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012005') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012007'), '012007', (SELECT id FROM ref_district WHERE code = 'HP'), 96, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012007') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012008'), '012008', (SELECT id FROM ref_district WHERE code = 'HP'), 86, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012008') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012009'), '012009', (SELECT id FROM ref_district WHERE code = 'HP'), 76, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012009') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012010'), '012010', (SELECT id FROM ref_district WHERE code = 'HP'), 96, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012010') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012002'), '012002', (SELECT id FROM ref_district WHERE code = 'HP'), 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '012006'), '012006', (SELECT id FROM ref_district WHERE code = 'HP'), 38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '012006') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042001'), '042001', (SELECT id FROM ref_district WHERE code = 'XH'), 52, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042008'), '042008', (SELECT id FROM ref_district WHERE code = 'XH'), 90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042008') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042035'), '042035', (SELECT id FROM ref_district WHERE code = 'XH'), 89, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042035') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '043015'), '043015', (SELECT id FROM ref_district WHERE code = 'XH'), 78, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '043015') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042002'), '042002', (SELECT id FROM ref_district WHERE code = 'XH'), 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '042036'), '042036', (SELECT id FROM ref_district WHERE code = 'XH'), 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '042036') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'XH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '052001'), '052001', (SELECT id FROM ref_district WHERE code = 'CN'), 51, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '052001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CN') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '052002'), '052002', (SELECT id FROM ref_district WHERE code = 'CN'), 72, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '052002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CN') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '053004'), '053004', (SELECT id FROM ref_district WHERE code = 'CN'), 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '053004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CN') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062001'), '062001', (SELECT id FROM ref_district WHERE code = 'JA'), 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062002'), '062002', (SELECT id FROM ref_district WHERE code = 'JA'), 67, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062003'), '062003', (SELECT id FROM ref_district WHERE code = 'JA'), 67, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062003') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062004'), '062004', (SELECT id FROM ref_district WHERE code = 'JA'), 74, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '062011'), '062011', (SELECT id FROM ref_district WHERE code = 'JA'), 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '062011') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '063004'), '063004', (SELECT id FROM ref_district WHERE code = 'JA'), 53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '063004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '064001'), '064001', (SELECT id FROM ref_district WHERE code = 'JA'), 44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '064001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '072001'), '072001', (SELECT id FROM ref_district WHERE code = 'PT'), 84, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '072001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PT') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '072002'), '072002', (SELECT id FROM ref_district WHERE code = 'PT'), 82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '072002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PT') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '073003'), '073003', (SELECT id FROM ref_district WHERE code = 'PT'), 84, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '073003') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PT') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '073082'), '073082', (SELECT id FROM ref_district WHERE code = 'PT'), 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '073082') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PT') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '092001'), '092001', (SELECT id FROM ref_district WHERE code = 'HK'), 76, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '092001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HK') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '092002'), '092002', (SELECT id FROM ref_district WHERE code = 'HK'), 71, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '092002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HK') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '093001'), '093001', (SELECT id FROM ref_district WHERE code = 'HK'), 56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '093001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'HK') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '102004'), '102004', (SELECT id FROM ref_district WHERE code = 'YP'), 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '102004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'YP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '102032'), '102032', (SELECT id FROM ref_district WHERE code = 'YP'), 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '102032') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'YP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '103002'), '103002', (SELECT id FROM ref_district WHERE code = 'YP'), 84, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '103002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'YP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '122001'), '122001', (SELECT id FROM ref_district WHERE code = 'MH'), 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '122001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '123001'), '123001', (SELECT id FROM ref_district WHERE code = 'MH'), 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '123001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '122002'), '122002', (SELECT id FROM ref_district WHERE code = 'MH'), 69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '122002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '122003'), '122003', (SELECT id FROM ref_district WHERE code = 'MH'), 86, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '122003') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '122004'), '122004', (SELECT id FROM ref_district WHERE code = 'MH'), 69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '122004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'MH') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '132001'), '132001', (SELECT id FROM ref_district WHERE code = 'BS'), 101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '132001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '132002'), '132002', (SELECT id FROM ref_district WHERE code = 'BS'), 101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '132002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '133001'), '133001', (SELECT id FROM ref_district WHERE code = 'BS'), 98, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '133001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '132003'), '132003', (SELECT id FROM ref_district WHERE code = 'BS'), 34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '132003') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '133003'), '133003', (SELECT id FROM ref_district WHERE code = 'BS'), 49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '133003') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'BS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '142001'), '142001', (SELECT id FROM ref_district WHERE code = 'JD'), 87, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '142001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '142002'), '142002', (SELECT id FROM ref_district WHERE code = 'JD'), 105, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '142002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '142004'), '142004', (SELECT id FROM ref_district WHERE code = 'JD'), 35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '142004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152001'), '152001', (SELECT id FROM ref_district WHERE code = 'PD'), 109, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152002'), '152002', (SELECT id FROM ref_district WHERE code = 'PD'), 109, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152004'), '152004', (SELECT id FROM ref_district WHERE code = 'PD'), 140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '153001'), '153001', (SELECT id FROM ref_district WHERE code = 'PD'), 109, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '153001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '153004'), '153004', (SELECT id FROM ref_district WHERE code = 'PD'), 94, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '153004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '153005'), '153005', (SELECT id FROM ref_district WHERE code = 'PD'), 94, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '153005') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '151078'), '151078', (SELECT id FROM ref_district WHERE code = 'PD'), 94, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '151078') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '152005'), '152005', (SELECT id FROM ref_district WHERE code = 'PD'), 56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '152005') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'PD') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '162000'), '162000', (SELECT id FROM ref_district WHERE code = 'JS'), 78, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '162000') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '163002'), '163002', (SELECT id FROM ref_district WHERE code = 'JS'), 78, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '163002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'JS') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '172001'), '172001', (SELECT id FROM ref_district WHERE code = 'SJ'), 82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '172001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '173001'), '173001', (SELECT id FROM ref_district WHERE code = 'SJ'), 82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '173001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '172002'), '172002', (SELECT id FROM ref_district WHERE code = 'SJ'), 33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '172002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '172004'), '172004', (SELECT id FROM ref_district WHERE code = 'SJ'), 18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '172004') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '174003'), '174003', (SELECT id FROM ref_district WHERE code = 'SJ'), 82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '174003') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'SJ') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '182001'), '182001', (SELECT id FROM ref_district WHERE code = 'QP'), 112, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '182001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'QP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '183002'), '183002', (SELECT id FROM ref_district WHERE code = 'QP'), 112, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '183002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'QP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '182002'), '182002', (SELECT id FROM ref_district WHERE code = 'QP'), 49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '182002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'QP') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '202001'), '202001', (SELECT id FROM ref_district WHERE code = 'FX'), 87, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '202001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'FX') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '202002'), '202002', (SELECT id FROM ref_district WHERE code = 'FX'), 43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '202002') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'FX') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '512000'), '512000', (SELECT id FROM ref_district WHERE code = 'CM'), 62, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '512000') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CM') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_quota_allocation_district (year, school_id, school_code, district_id, quota_count, created_at, updated_at) SELECT 2025, (SELECT id FROM ref_school WHERE code = '512001'), '512001', (SELECT id FROM ref_district WHERE code = 'CM'), 31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_school WHERE code = '512001') AND EXISTS (SELECT 1 FROM ref_district WHERE code = 'CM') ON CONFLICT (year, school_code, district_id) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;

-- Verify insert - show quota by school
SELECT s.code, s.full_name, d.code as district_code, qad.quota_count
FROM ref_quota_allocation_district qad
JOIN ref_school s ON qad.school_code = s.code
JOIN ref_district d ON qad.district_id = d.id
WHERE qad.year = 2025
ORDER BY s.code, d.code;