-- =============================================================================
-- 2025年初中学校数据（从名额分配到校数据中提取）
-- =============================================================================
-- Generated: 2026-02-12 23:23:43
-- Source: 2025年名额分配到校.csv

-- Delete existing 2025 data
DELETE FROM ref_middle_school WHERE data_year = 2025;

-- Insert 2025 middle school data
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061001', '上海市市西初级中学', '市西初级中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061002', '上海市育才初级中学', '育才初级中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061003', '上海市静安区协和双语培明学校', '协和双语培明学校', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061005', '上海市时代中学', '时代中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061008', '上海市五四中学', '五四中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061009', '民办上海上外静安外国语中学', '民办上海上外静安外国语中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061050', '上海市静安区市北初级中学北校', '市北初级中学北校', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061051', '上海市新中初级中学', '新中初级中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061053', '上海市静安区实验中学', '实验中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061055', '上海市朝阳中学', '朝阳中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061059', '上海市市北初级中学', '市北初级中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061060', '上海市风华初级中学', '风华初级中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061061', '上海市彭浦初级中学', '彭浦初级中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061062', '上海外国语大学苏河湾实验中学', '上海外国语大学苏河湾实验中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061066', '上海市青云中学', '青云中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061071', '上海市岭南中学', '岭南中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061072', '上海市保德中学', '保德中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061073', '上海市彭浦第三中学', '彭浦第三中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '061074', '上海市彭浦第四中学', '彭浦第四中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '062011', '上海市回民中学', '回民中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '063001', '上海市民立中学', '民立中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '063002', '上海市第一中学', '第一中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '063008', '上海市久隆模范中学', '久隆模范中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '063077', '上海市闸北第八中学', '闸北第八中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '064001', '上海市华东模范中学', '华东模范中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '064003', '同济大学附属七一中学', '同济大学附属七一中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '064007', '上海市向东中学', '向东中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '064020', '上海田家炳中学', '上海田家炳中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '064021', '上海市民办扬波中学', '民办扬波中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '064023', '上海市民办新和中学', '民办新和中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '064024', '上海市民办风范中学', '民办风范中学', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '065001', '上海市爱国学校', '爱国学校', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '065002', '上海市静安区教育学院附属学校', '教育学院附属学校', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '065056', '上海市华灵学校', '华灵学校', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '065057', '上海市三泉学校', '三泉学校', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '065058', '上海戏剧学院附属静安学校', '上海戏剧学院附属静安学校', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;
INSERT INTO ref_middle_school (code, name, short_name, district_id, school_nature_id, is_non_selective, data_year, is_active, created_at, updated_at) SELECT '065078', '上海市静安区大宁国际学校', '大宁国际学校', (SELECT id FROM ref_district WHERE code = 'JA'), 'PUBLIC', TRUE, 2025, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = 'JA') ON CONFLICT (code, data_year) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, district_id = EXCLUDED.district_id, is_active = TRUE, updated_at = CURRENT_TIMESTAMP;

-- Verify insert - show middle schools by district
SELECT d.code, d.name, COUNT(*) as school_count
FROM ref_middle_school ms
JOIN ref_district d ON ms.district_id = d.id
WHERE ms.data_year = 2025
GROUP BY d.code, d.name
ORDER BY d.code;