-- 初中梯队/区内排名/声誉分回填(来源: sh_zhongkao_2026 排行榜, 声誉为主观口碑仅供参考)
-- 依赖: db/migrations/008_add_middle_school_2026_stats_columns.sql
BEGIN;

UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=12 AND name='上海市张江集团中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=12 AND name='上海民办浦东交中初级中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=3, reputation_score=92 WHERE district_id=12 AND name='上海市实验学校东校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=4, reputation_score=92 WHERE district_id=12 AND name='上海市建平中学西校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=5, reputation_score=92 WHERE district_id=12 AND name='上海民办华曜浦东实验学校';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=12 AND name='上海交通大学附属浦东实验中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=12 AND name='上海中学东校';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=12 AND name='上海立信会计金融学院附属学校';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=12 AND name='上海市建平香梅中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=12 AND name='上海市南汇第二中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=12 AND name='上海市南汇第四中学';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=12 AND name='上海市浦东模范实验中学';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=12 AND name='上海浦东新区民办正达外国语学校';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=12 AND name='上海市川沙中学华夏西校';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=12 AND name='上海市浦东新区进才中学东校';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=12 AND name='上海市进才中学北校';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=12 AND name='华东师范大学附属东昌中学南校';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=12 AND name='上海市建平实验地杰中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=12 AND name='上海市建平实验张江中学';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=12 AND name='上海市临港实验中学';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=12 AND name='上海市傅雷中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=12 AND name='上海市浦东模范中学';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=12 AND name='上海市杨园中学';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=12 AND name='上海市浦东新区建平临港中学';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=12 AND name='上海市民办中芯学校';
UPDATE ref_middle_school SET district_rank=26 WHERE district_id=12 AND name='上海市实验学校南校';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=12 AND name='上海市澧溪中学';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=12 AND name='上海市清流中学';
UPDATE ref_middle_school SET district_rank=29 WHERE district_id=12 AND name='上海市浦东新区进才实验中学南校';
UPDATE ref_middle_school SET district_rank=30 WHERE district_id=12 AND name='上海市北蔡中学';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=12 AND name='上海市民办金苹果学校';
UPDATE ref_middle_school SET district_rank=32 WHERE district_id=12 AND name='上海市上南中学南校';
UPDATE ref_middle_school SET district_rank=33 WHERE district_id=12 AND name='上海市洋泾菊园实验学校';
UPDATE ref_middle_school SET district_rank=34 WHERE district_id=12 AND name='上海市金杨中学';
UPDATE ref_middle_school SET district_rank=35 WHERE district_id=12 AND name='上海市浦东新区进才中学南校';
UPDATE ref_middle_school SET district_rank=36 WHERE district_id=12 AND name='上海市五三中学';
UPDATE ref_middle_school SET district_rank=37 WHERE district_id=12 AND name='上海市浦兴中学';
UPDATE ref_middle_school SET district_rank=38 WHERE district_id=12 AND name='上海市侨光中学';
UPDATE ref_middle_school SET district_rank=39 WHERE district_id=12 AND name='上海市浦东新区三灶实验中学';
UPDATE ref_middle_school SET district_rank=40 WHERE district_id=12 AND name='上海市康城学校';
UPDATE ref_middle_school SET district_rank=41 WHERE district_id=12 AND name='上海市南汇第三中学';
UPDATE ref_middle_school SET district_rank=42 WHERE district_id=12 AND name='上海市浦东新区建平培德实验中学';
UPDATE ref_middle_school SET district_rank=43 WHERE district_id=12 AND name='上海市洋泾中学南校';
UPDATE ref_middle_school SET district_rank=44 WHERE district_id=12 AND name='上海市东昌东校';
UPDATE ref_middle_school SET district_rank=45 WHERE district_id=12 AND name='华东师范大学张江实验中学';
UPDATE ref_middle_school SET district_rank=46 WHERE district_id=12 AND name='上海市华林中学';
UPDATE ref_middle_school SET district_rank=47 WHERE district_id=12 AND name='上海浦东新区民办恒洋外国语学校';
UPDATE ref_middle_school SET district_rank=48 WHERE district_id=12 AND name='上海市浦东模范中学东校';
UPDATE ref_middle_school SET district_rank=49 WHERE district_id=12 AND name='上海市竹园中学';
UPDATE ref_middle_school SET district_rank=50 WHERE district_id=12 AND name='上海市杨思中学';
UPDATE ref_middle_school SET district_rank=51 WHERE district_id=12 AND name='上海师范大学附属浦东临港中学';
UPDATE ref_middle_school SET district_rank=52 WHERE district_id=12 AND name='上海市王港中学';
UPDATE ref_middle_school SET district_rank=53 WHERE district_id=12 AND name='上海市香山中学';
UPDATE ref_middle_school SET district_rank=54 WHERE district_id=12 AND name='上海市南汇第一中学';
UPDATE ref_middle_school SET district_rank=55 WHERE district_id=12 AND name='上海民办启能东方外国语学校';
UPDATE ref_middle_school SET district_rank=56 WHERE district_id=12 AND name='上海市浦东新区进才森兰实验中学';
UPDATE ref_middle_school SET district_rank=57 WHERE district_id=12 AND name='上海市航头学校';
UPDATE ref_middle_school SET district_rank=58 WHERE district_id=12 AND name='上海市浦东新区新场实验中学';
UPDATE ref_middle_school SET district_rank=59 WHERE district_id=12 AND name='上海第二工业大学附属龚路中学';
UPDATE ref_middle_school SET district_rank=60 WHERE district_id=12 AND name='上海市实验学校附属光明学校';
UPDATE ref_middle_school SET district_rank=61 WHERE district_id=12 AND name='上海市浦东新区懿德中学';
UPDATE ref_middle_school SET district_rank=62 WHERE district_id=12 AND name='上海市长岛中学';
UPDATE ref_middle_school SET district_rank=63 WHERE district_id=12 AND name='上海市陆行中学南校';
UPDATE ref_middle_school SET district_rank=64 WHERE district_id=12 AND name='上海市顾路中学';
UPDATE ref_middle_school SET district_rank=65 WHERE district_id=12 AND name='上海市南汇第五中学';
UPDATE ref_middle_school SET district_rank=66 WHERE district_id=12 AND name='上海市三林中学北校';
UPDATE ref_middle_school SET district_rank=67 WHERE district_id=12 AND name='上海市浦东新区建平南汇实验学校';
UPDATE ref_middle_school SET district_rank=68 WHERE district_id=12 AND name='上海市浦东新区建平康梧中学';
UPDATE ref_middle_school SET district_rank=69 WHERE district_id=12 AND name='上海市洪山中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=70, reputation_score=76 WHERE district_id=12 AND name='上海市进才实验中学';
UPDATE ref_middle_school SET district_rank=71 WHERE district_id=12 AND name='上海市上南中学北校';
UPDATE ref_middle_school SET district_rank=72 WHERE district_id=12 AND name='上海立信会计金融学院附属高行中学';
UPDATE ref_middle_school SET district_rank=73 WHERE district_id=12 AND name='上海市育人中学';
UPDATE ref_middle_school SET district_rank=74 WHERE district_id=12 AND name='上海市沪新中学';
UPDATE ref_middle_school SET district_rank=75 WHERE district_id=12 AND name='上海戏剧学院附属浦东实验中学';
UPDATE ref_middle_school SET district_rank=76 WHERE district_id=12 AND name='上海市浦东外国语学校东校';
UPDATE ref_middle_school SET district_rank=77 WHERE district_id=12 AND name='上海市六灶中学';
UPDATE ref_middle_school SET district_rank=78 WHERE district_id=12 AND name='上海市三林中学东校';
UPDATE ref_middle_school SET district_rank=79 WHERE district_id=12 AND name='上海市蔡路中学';
UPDATE ref_middle_school SET district_rank=80 WHERE district_id=12 AND name='华东师范大学第二附属中学前滩学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=81, reputation_score=76 WHERE district_id=12 AND name='上海师范大学附属高桥实验中学';
UPDATE ref_middle_school SET district_rank=82 WHERE district_id=12 AND name='上海市陆行中学北校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=83, reputation_score=76 WHERE district_id=12 AND name='上海市罗山中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=84, reputation_score=76 WHERE district_id=12 AND name='上海浦东新区民办欣竹中学';
UPDATE ref_middle_school SET district_rank=85 WHERE district_id=12 AND name='上海市东沟中学';
UPDATE ref_middle_school SET district_rank=86 WHERE district_id=12 AND name='上海市江镇中学';
UPDATE ref_middle_school SET district_rank=87 WHERE district_id=12 AND name='上海中医药大学附属浦东鹤沙学校';
UPDATE ref_middle_school SET district_rank=88 WHERE district_id=12 AND name='上海市黄路学校';
UPDATE ref_middle_school SET district_rank=89 WHERE district_id=12 AND name='上海市凌桥中学';
UPDATE ref_middle_school SET district_rank=90 WHERE district_id=12 AND name='上海市大团中学';
UPDATE ref_middle_school SET district_rank=91 WHERE district_id=12 AND name='上海市孙桥中学';
UPDATE ref_middle_school SET district_rank=92 WHERE district_id=12 AND name='上海市川沙中学南校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=93, reputation_score=76 WHERE district_id=12 AND name='上海市建平实验中学';
UPDATE ref_middle_school SET district_rank=94 WHERE district_id=12 AND name='上海浦东新区民办协和双语学校';
UPDATE ref_middle_school SET district_rank=95 WHERE district_id=12 AND name='上海市高东中学';
UPDATE ref_middle_school SET district_rank=96 WHERE district_id=12 AND name='上海市浦东新区进才万祥学校';
UPDATE ref_middle_school SET district_rank=97 WHERE district_id=12 AND name='上海市民办平和学校';
UPDATE ref_middle_school SET district_rank=98 WHERE district_id=12 AND name='上海市浦泾中学';
UPDATE ref_middle_school SET district_rank=99 WHERE district_id=12 AND name='上海市育民中学';
UPDATE ref_middle_school SET district_rank=100 WHERE district_id=12 AND name='上海市民办尚德实验学校';
UPDATE ref_middle_school SET district_rank=101 WHERE district_id=12 AND name='上海民办光华中学';
UPDATE ref_middle_school SET district_rank=102 WHERE district_id=12 AND name='上海市新云台中学';
UPDATE ref_middle_school SET district_rank=103 WHERE district_id=12 AND name='上海市合庆中学';
UPDATE ref_middle_school SET district_rank=104 WHERE district_id=12 AND name='上海市泥城中学';
UPDATE ref_middle_school SET district_rank=105 WHERE district_id=12 AND name='上海市宣桥学校';
UPDATE ref_middle_school SET district_rank=106 WHERE district_id=12 AND name='上海市浦东新区教育学院附属实验中学';
UPDATE ref_middle_school SET district_rank=107 WHERE district_id=12 AND name='上海市绿川学校';
UPDATE ref_middle_school SET district_rank=108 WHERE district_id=12 AND name='上海市施湾中学';
UPDATE ref_middle_school SET district_rank=109 WHERE district_id=12 AND name='上海市金川中学';
UPDATE ref_middle_school SET district_rank=110 WHERE district_id=12 AND name='上海市泾南中学';
UPDATE ref_middle_school SET district_rank=111 WHERE district_id=12 AND name='上海市浦东新区彭镇中学';
UPDATE ref_middle_school SET district_rank=112 WHERE district_id=12 AND name='上海市三灶学校';
UPDATE ref_middle_school SET district_rank=113 WHERE district_id=12 AND name='上海市东林中学';
UPDATE ref_middle_school SET district_rank=114 WHERE district_id=12 AND name='上海市历城中学';
UPDATE ref_middle_school SET district_rank=115 WHERE district_id=12 AND name='上海市黄楼中学';
UPDATE ref_middle_school SET district_rank=116 WHERE district_id=12 AND name='上海师范大学附属浦东秋萍学校';
UPDATE ref_middle_school SET district_rank=117 WHERE district_id=12 AND name='上海市书院中学';
UPDATE ref_middle_school SET district_rank=118 WHERE district_id=12 AND name='上海市浦东教育发展研究院附属中学';
UPDATE ref_middle_school SET district_rank=119 WHERE district_id=12 AND name='上海市周浦育才学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=120, reputation_score=58 WHERE district_id=12 AND name='上海市致远中学';
UPDATE ref_middle_school SET district_rank=121 WHERE district_id=12 AND name='上海市坦直中学';
UPDATE ref_middle_school SET district_rank=122 WHERE district_id=12 AND name='上海市六团中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=123, reputation_score=58 WHERE district_id=12 AND name='上海市上南中学东校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=124, reputation_score=58 WHERE district_id=12 AND name='上海市洋泾中学东校';
UPDATE ref_middle_school SET district_rank=125 WHERE district_id=12 AND name='上海市老港中学';
UPDATE ref_middle_school SET district_rank=126 WHERE district_id=12 AND name='上海市三墩学校';
UPDATE ref_middle_school SET district_rank=127 WHERE district_id=12 AND name='上海市东海学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=2 AND name='向明初级中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=2 AND name='大同初级中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=3, reputation_score=92 WHERE district_id=2 AND name='格致初级中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=4, reputation_score=92 WHERE district_id=2 AND name='民办立达中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=2 AND name='大境初级中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=2 AND name='中山学校';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=2 AND name='尚文中学';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=2 AND name='交附黄浦实验';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=2 AND name='市十中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=2 AND name='光明初级中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=2 AND name='敬业初级中学';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=2 AND name='市八初级中学';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=2 AND name='金陵中学';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=2 AND name='民办震旦外国语';
UPDATE ref_middle_school SET tier='二梯队', district_rank=15, reputation_score=76 WHERE district_id=2 AND name='卢湾中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=2 AND name='上音比乐中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=17, reputation_score=76 WHERE district_id=2 AND name='民办永昌学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=18, reputation_score=76 WHERE district_id=2 AND name='民办明珠中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=2 AND name='储能中学';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=2 AND name='清华中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=21, reputation_score=58 WHERE district_id=2 AND name='市南中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=2 AND name='康德双语实验学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=3 AND name='上海市徐汇区上汇实验学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=3 AND name='上海市世外中学';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=3 AND name='上海民办南模中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=4, reputation_score=92 WHERE district_id=3 AND name='上海市民办华育中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=3 AND name='上海市第五十四中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=3 AND name='上海市徐汇中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=3 AND name='上海市位育实验学校';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=3 AND name='上海民办位育中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=3 AND name='上海市徐汇区教育学院附属实验中学南部分校';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=3 AND name='上海市第二初级中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=3 AND name='上海市田林第二中学';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=3 AND name='上海市紫阳中学';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=3 AND name='上海市梅园中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=14, reputation_score=76 WHERE district_id=3 AND name='上海市西南模范中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=3 AND name='徐汇南校';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=3 AND name='上海市田林中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=17, reputation_score=76 WHERE district_id=3 AND name='上海市位育初级中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=18, reputation_score=76 WHERE district_id=3 AND name='上海市南洋模范初级中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=3 AND name='上海市零陵中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=20, reputation_score=76 WHERE district_id=3 AND name='上海市徐汇区教育学院附属实验中学';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=3 AND name='上海市南洋初级中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=22, reputation_score=76 WHERE district_id=3 AND name='上海市西南位育中学';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=3 AND name='上海市中国中学';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=3 AND name='上海市康健外国语实验中学';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=3 AND name='上海市汾阳中学';
UPDATE ref_middle_school SET district_rank=26 WHERE district_id=3 AND name='华东理工大学附属中学';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=3 AND name='上海市第四中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=28, reputation_score=58 WHERE district_id=3 AND name='上海市园南中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=29, reputation_score=58 WHERE district_id=3 AND name='上海师范大学第三附属实验学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=30, reputation_score=58 WHERE district_id=3 AND name='上海市田林第三中学';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=3 AND name='上海市龙苑中学';
UPDATE ref_middle_school SET district_rank=1 WHERE district_id=4 AND name='上海市开元学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=4 AND name='上海市第三女子初级中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=3, reputation_score=92 WHERE district_id=4 AND name='上海市延安初级中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=4 AND name='华东政法大学附属中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=4 AND name='上海市仙霞高级中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=4 AND name='上海市新泾中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=4 AND name='上海市天山初级中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=8, reputation_score=76 WHERE district_id=4 AND name='上海市娄山中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=9, reputation_score=76 WHERE district_id=4 AND name='上海市西延安中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=4 AND name='上海市延安实验初级中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=4 AND name='上海市民办新世纪中学';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=4 AND name='上海市姚连生中学';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=4 AND name='上海市泸定中学';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=4 AND name='上海市天山第二中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=4 AND name='上海市虹桥中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=16, reputation_score=58 WHERE district_id=4 AND name='上海市建青实验学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=17, reputation_score=58 WHERE district_id=4 AND name='上海市复旦初级中学';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=4 AND name='上海市西郊学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=5 AND name='上海市民办扬波中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=5 AND name='上海市静安区教育学院附属学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=3, reputation_score=92 WHERE district_id=5 AND name='上海市市北初级中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=5 AND name='上海外国语大学苏河湾实验中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=5 AND name='上海市新中初级中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=5 AND name='上海市静安区实验中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=5 AND name='上海市静安区市北初级中学北校';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=5 AND name='上海市时代中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=5 AND name='上海市闸北第八中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=5 AND name='上海市青云中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=5 AND name='上海市彭浦初级中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=12, reputation_score=76 WHERE district_id=5 AND name='上海市风华初级中学';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=5 AND name='上海戏剧学院附属静安学校';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=5 AND name='上海市民办新和中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=5 AND name='上海市保德中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=5 AND name='上海市静安区协和双语培明学校';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=5 AND name='上海市彭浦第三中学';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=5 AND name='上海市华灵学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=19, reputation_score=76 WHERE district_id=5 AND name='上海市静安区大宁国际学校';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=5 AND name='上海市朝阳中学';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=5 AND name='上海市育才初级中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=5 AND name='上海市岭南中学';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=5 AND name='上海市华东模范中学';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=5 AND name='上海市向东中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=25, reputation_score=76 WHERE district_id=5 AND name='上海市市西初级中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=26, reputation_score=76 WHERE district_id=5 AND name='同济大学附属七一中学';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=5 AND name='上海市五四中学';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=5 AND name='上海市彭浦第四中学';
UPDATE ref_middle_school SET district_rank=29 WHERE district_id=5 AND name='上海市三泉学校';
UPDATE ref_middle_school SET district_rank=30 WHERE district_id=5 AND name='上海市爱国学校';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=5 AND name='上海市民立中学';
UPDATE ref_middle_school SET district_rank=32 WHERE district_id=5 AND name='上海市第一中学';
UPDATE ref_middle_school SET district_rank=33 WHERE district_id=5 AND name='上海市回民中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=34, reputation_score=58 WHERE district_id=5 AND name='民办上海上外静安外国语中学';
UPDATE ref_middle_school SET district_rank=35 WHERE district_id=5 AND name='上海市久隆模范中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=36, reputation_score=58 WHERE district_id=5 AND name='上海田家炳中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=6 AND name='上海华东师范大学附属进华中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=6 AND name='上海市梅陇中学';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=6 AND name='上海市甘泉外国语中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=6 AND name='上海市曹杨第二中学附属实验中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=6 AND name='同济大学第二附属中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=6 AND name='上海市中远实验学校';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=6 AND name='上海兰田中学';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=6 AND name='上海市洛川学校';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=6 AND name='上海市民办新黄浦实验学校';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=6 AND name='上海理工大学附属普陀实验学校';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=6 AND name='上海市曹杨第二中学附属学校';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=6 AND name='上海市万里城实验学校';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=6 AND name='上海市真北中学';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=6 AND name='上海外国语大学尚阳外国语学校';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=6 AND name='上海市延河中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=6 AND name='上海师范大学附属第二实验学校';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=6 AND name='华东师范大学附属外国语实验学校';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=6 AND name='上海市长征中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=6 AND name='上海市普陀区教育学院附属中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=20, reputation_score=76 WHERE district_id=6 AND name='上海培佳双语学校';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=6 AND name='上海市曹杨中学附属学校';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=6 AND name='上海市宜川中学附属学校';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=6 AND name='上海市铜川学校';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=6 AND name='上海市洵阳中学';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=6 AND name='上海市怒江中学';
UPDATE ref_middle_school SET district_rank=26 WHERE district_id=6 AND name='上海市曹杨中学';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=6 AND name='上海市普陀区梅陇实验中学';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=6 AND name='上海市文达学校';
UPDATE ref_middle_school SET district_rank=29 WHERE district_id=6 AND name='上海市晋元高级中学附属学校南校';
UPDATE ref_middle_school SET district_rank=30 WHERE district_id=6 AND name='上海市普陀区教育学院附属学校';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=6 AND name='上海市北海中学';
UPDATE ref_middle_school SET district_rank=32 WHERE district_id=6 AND name='上海市子长学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=33, reputation_score=76 WHERE district_id=6 AND name='上海市晋元高级中学附属学校';
UPDATE ref_middle_school SET district_rank=34 WHERE district_id=6 AND name='上海市桃浦中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=35, reputation_score=76 WHERE district_id=6 AND name='华东师范大学第四附属中学';
UPDATE ref_middle_school SET district_rank=36 WHERE district_id=6 AND name='上海市新杨中学';
UPDATE ref_middle_school SET district_rank=37 WHERE district_id=6 AND name='上海市金鼎学校';
UPDATE ref_middle_school SET district_rank=38 WHERE district_id=6 AND name='上海安生学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=39, reputation_score=58 WHERE district_id=6 AND name='上海市江宁学校';
UPDATE ref_middle_school SET district_rank=40 WHERE district_id=6 AND name='上海音乐学院附属安师实验中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=41, reputation_score=58 WHERE district_id=6 AND name='上海市沙田学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=7 AND name='上海市民办新华初级中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=7 AND name='上海市民办新复兴初级中学';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=7 AND name='上海市鲁迅初级中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=7 AND name='上海音乐学院虹口区实验中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=7 AND name='上海市继光初级中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=7 AND name='上海市曲阳第二中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=7 AND name='上海市海南中学';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=7 AND name='华东师范大学第一附属初级中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=7 AND name='上海市复兴实验中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=10, reputation_score=76 WHERE district_id=7 AND name='上海市长青学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=11, reputation_score=76 WHERE district_id=7 AND name='上海市民办迅行中学';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=7 AND name='上海市丰镇中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=13, reputation_score=76 WHERE district_id=7 AND name='上海市民办新北郊初级中学';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=7 AND name='上海市北郊学校';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=7 AND name='上海市第五十二中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=7 AND name='上海世外教育附属虹口区欧阳学校';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=7 AND name='上海市钟山初级中学';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=7 AND name='上海市虹口区教育学院实验中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=7 AND name='上海民办克勒外国语学校';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=7 AND name='同济大学附属澄衷中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=21, reputation_score=58 WHERE district_id=7 AND name='上海市虹口实验学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=22, reputation_score=58 WHERE district_id=7 AND name='上海市江湾初级中学';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=7 AND name='上海师范大学附属虹口中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=8 AND name='上海市存志学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=8 AND name='复旦大学第二附属学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=3, reputation_score=92 WHERE district_id=8 AND name='上海民办兰生中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=8 AND name='上海市辽阳中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=8 AND name='上海市同济初级中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=8 AND name='上海市鞍山初级中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=8 AND name='上海市惠民中学';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=8 AND name='上海市思源中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=8 AND name='上海市十五中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=8 AND name='上海市新大桥中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=11, reputation_score=76 WHERE district_id=8 AND name='上海民办杨浦凯慧初级中学';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=8 AND name='上海市三门中学（上海财经大学附属初级中学）';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=8 AND name='上海理工大学附属初级中学';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=8 AND name='上海市控江初级中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=8 AND name='上海市鞍山实验中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=8 AND name='上海市杨浦初级中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=17, reputation_score=76 WHERE district_id=8 AND name='上海杨浦双语学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=18, reputation_score=76 WHERE district_id=8 AND name='上海民办杨浦实验学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=19, reputation_score=76 WHERE district_id=8 AND name='上海同大实验学校';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=8 AND name='上海市杨浦区教育学院附属中学';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=8 AND name='上海市建设初级中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=8 AND name='上海市国和中学';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=8 AND name='上海市同济第二初级中学';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=8 AND name='上海市包头中学';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=8 AND name='上海市二十五中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=26, reputation_score=58 WHERE district_id=8 AND name='上海市铁岭中学';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=8 AND name='上海理工大学附属实验初级中学';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=8 AND name='上海市东辽阳中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=29, reputation_score=58 WHERE district_id=8 AND name='上海音乐学院实验学校';
UPDATE ref_middle_school SET district_rank=1 WHERE district_id=9 AND name='上海民办圣华紫竹双语学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=9 AND name='上海市文来中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=3, reputation_score=92 WHERE district_id=9 AND name='华东师范大学第二附属中学附属初级中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=4, reputation_score=92 WHERE district_id=9 AND name='上海市民办上宝中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=9 AND name='上海交通大学附属第二中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=9 AND name='上海博世凯外国语学校';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=9 AND name='上海市民办德英乐实验学校';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=9 AND name='上海市莘光学校';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=9 AND name='上海尚师初级中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=9 AND name='上海市闵行区北桥中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=9 AND name='上海市闵行区明星学校';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=9 AND name='上海市罗阳中学';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=9 AND name='上海市闵行区田园外国语中学';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=9 AND name='上海市七宝中学附属鑫都实验中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=9 AND name='上海市民办万源城协和双语学校';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=9 AND name='上海市闵行区颛桥中学';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=9 AND name='上海世外教育附属浦江外国语学校';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=9 AND name='上海市闵行区马桥复旦万科实验中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=9 AND name='上海市龙柏中学';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=9 AND name='上海市师资培训中心附属闵行实验中学';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=9 AND name='上海市骏博外国语学校';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=9 AND name='上海市闵行区华漕学校';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=9 AND name='上海市闵行区上虹中学';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=9 AND name='上海市七宝实验中学';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=9 AND name='上海市闵行区龙茗中学';
UPDATE ref_middle_school SET district_rank=26 WHERE district_id=9 AND name='上海师范大学康城实验学校';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=9 AND name='华东师范大学附属闵行永德学校';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=9 AND name='上海市闵行区浦航实验中学';
UPDATE ref_middle_school SET district_rank=29 WHERE district_id=9 AND name='上海市闵行中学附属实验中学';
UPDATE ref_middle_school SET district_rank=30 WHERE district_id=9 AND name='上海市闵行区文来实验学校';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=9 AND name='上海交通大学附属闵行马桥实验学校';
UPDATE ref_middle_school SET district_rank=32 WHERE district_id=9 AND name='上海师范大学附属闵行第三中学';
UPDATE ref_middle_school SET district_rank=33 WHERE district_id=9 AND name='上海中医药大学附属闵行晶城中学';
UPDATE ref_middle_school SET district_rank=34 WHERE district_id=9 AND name='上海市闵行第三中学';
UPDATE ref_middle_school SET district_rank=35 WHERE district_id=9 AND name='上海市闵行区君莲学校';
UPDATE ref_middle_school SET district_rank=36 WHERE district_id=9 AND name='华东理工大学附属闵行梅陇实验学校';
UPDATE ref_middle_school SET district_rank=37 WHERE district_id=9 AND name='上海市吴泾中学';
UPDATE ref_middle_school SET district_rank=38 WHERE district_id=9 AND name='上海市闵行区鹤北初级中学';
UPDATE ref_middle_school SET district_rank=39 WHERE district_id=9 AND name='上海市闵行区七宝文来学校';
UPDATE ref_middle_school SET district_rank=40 WHERE district_id=9 AND name='上海闵行区协和双语教科学校';
UPDATE ref_middle_school SET district_rank=41 WHERE district_id=9 AND name='上海市古美学校';
UPDATE ref_middle_school SET district_rank=42 WHERE district_id=9 AND name='上海市七宝中学附属闵行金都实验中学';
UPDATE ref_middle_school SET district_rank=43 WHERE district_id=9 AND name='上海市闵行区七宝第二中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=44, reputation_score=76 WHERE district_id=9 AND name='上海市民办文绮中学';
UPDATE ref_middle_school SET district_rank=45 WHERE district_id=9 AND name='上海市闵行区诸翟学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=46, reputation_score=76 WHERE district_id=9 AND name='上海市闵行区莘松中学';
UPDATE ref_middle_school SET district_rank=47 WHERE district_id=9 AND name='华东师范大学附属闵行虹桥学校';
UPDATE ref_middle_school SET district_rank=48 WHERE district_id=9 AND name='上海市闵行区浦江第二中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=49, reputation_score=76 WHERE district_id=9 AND name='上海市闵行区七宝第三中学';
UPDATE ref_middle_school SET district_rank=50 WHERE district_id=9 AND name='上海市民办协和双语尚音学校';
UPDATE ref_middle_school SET district_rank=51 WHERE district_id=9 AND name='上海市闵行区浦江第三中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=52, reputation_score=76 WHERE district_id=9 AND name='上海师范大学附属中学闵行实验学校';
UPDATE ref_middle_school SET district_rank=53 WHERE district_id=9 AND name='上海市航华中学';
UPDATE ref_middle_school SET district_rank=54 WHERE district_id=9 AND name='上海市闵行第四中学';
UPDATE ref_middle_school SET district_rank=55 WHERE district_id=9 AND name='上海市闵行区纪王学校';
UPDATE ref_middle_school SET district_rank=56 WHERE district_id=9 AND name='上海市马桥强恕学校';
UPDATE ref_middle_school SET district_rank=57 WHERE district_id=9 AND name='上海市闵行区浦江第一中学';
UPDATE ref_middle_school SET district_rank=58 WHERE district_id=9 AND name='上海市燎原双语学校';
UPDATE ref_middle_school SET district_rank=59 WHERE district_id=9 AND name='上海星河湾双语学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=60, reputation_score=58 WHERE district_id=9 AND name='上海市莘城学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=61, reputation_score=58 WHERE district_id=9 AND name='上海市实验学校西校';
UPDATE ref_middle_school SET district_rank=62 WHERE district_id=9 AND name='上海闵行区民办德闳学校';
UPDATE ref_middle_school SET district_rank=63 WHERE district_id=9 AND name='上海闵行区民办美高双语学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=10 AND name='上海民办华曜宝山实验学校';
UPDATE ref_middle_school SET district_rank=2 WHERE district_id=10 AND name='上海世外教育附属宝山大华实验学校';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=10 AND name='上海市宝山中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=10 AND name='上海师范大学附属宝山实验学校';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=10 AND name='上海市罗南中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=10 AND name='上海宝山区世外学校';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=10 AND name='上海市淞谊中学';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=10 AND name='上海市宝山区杨泰实验中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=10 AND name='上海市月浦实验学校';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=10 AND name='上海市同洲模范学校';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=10 AND name='上海市吴淞实验学校';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=10 AND name='上海市宝山实验学校分校';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=10 AND name='上海外国语大学附属宝山双语学校';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=10 AND name='上海大学附属宝山外国语学校';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=10 AND name='上海民办至德实验学校';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=10 AND name='上海民办宝莲中学';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=10 AND name='上海师范大学附属宝山经纬实验中学';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=10 AND name='上海市民办交华中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=10 AND name='上海市大场中学';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=10 AND name='上海市宝山区顾村科技园学校';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=10 AND name='上海市宝山区美兰湖中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=10 AND name='上海市刘行新华实验学校';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=10 AND name='上海市宝山区行知外国语学校';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=10 AND name='上海市宝山区求真中学北校';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=10 AND name='上海市宝山区上海大学附属中学实验学校';
UPDATE ref_middle_school SET district_rank=26 WHERE district_id=10 AND name='上海大学附属学校';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=10 AND name='华东师范大学宝山实验学校';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=10 AND name='上海市大华中学';
UPDATE ref_middle_school SET district_rank=29 WHERE district_id=10 AND name='上海市泗塘中学';
UPDATE ref_middle_school SET district_rank=30 WHERE district_id=10 AND name='上海市宝山区庙行实验学校';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=10 AND name='上海市教育学会宝山实验学校';
UPDATE ref_middle_school SET district_rank=32 WHERE district_id=10 AND name='上海市宝山区鹿鸣学校';
UPDATE ref_middle_school SET district_rank=33 WHERE district_id=10 AND name='上海市宝山区乐之中学';
UPDATE ref_middle_school SET district_rank=34 WHERE district_id=10 AND name='上海市宝山区共富实验学校';
UPDATE ref_middle_school SET district_rank=35 WHERE district_id=10 AND name='上海市宝山区南大实验学校';
UPDATE ref_middle_school SET district_rank=36 WHERE district_id=10 AND name='上海市存志附属宝山实验学校';
UPDATE ref_middle_school SET district_rank=37 WHERE district_id=10 AND name='上海市行知实验中学';
UPDATE ref_middle_school SET district_rank=38 WHERE district_id=10 AND name='上海师范大学附属宝山潜溪学校';
UPDATE ref_middle_school SET district_rank=39 WHERE district_id=10 AND name='上海市宝山区天馨学校';
UPDATE ref_middle_school SET district_rank=40 WHERE district_id=10 AND name='上海市宝山区新民实验学校';
UPDATE ref_middle_school SET district_rank=41 WHERE district_id=10 AND name='上海市长江第二中学';
UPDATE ref_middle_school SET district_rank=42 WHERE district_id=10 AND name='上海市宝山区顾村实验学校';
UPDATE ref_middle_school SET district_rank=43 WHERE district_id=10 AND name='上海市吴淞中学附属宝山实验学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=44, reputation_score=76 WHERE district_id=10 AND name='上海市宝山区教育学院附属中学';
UPDATE ref_middle_school SET district_rank=45 WHERE district_id=10 AND name='上海市宝山华曜附属罗泾中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=46, reputation_score=76 WHERE district_id=10 AND name='上海市宝山区求真中学';
UPDATE ref_middle_school SET district_rank=47 WHERE district_id=10 AND name='上海市宝山实验学校高境分校';
UPDATE ref_middle_school SET district_rank=48 WHERE district_id=10 AND name='上海市宝山区淞谊实验学校';
UPDATE ref_middle_school SET district_rank=49 WHERE district_id=10 AND name='上海农场学校';
UPDATE ref_middle_school SET district_rank=50 WHERE district_id=10 AND name='上海市宝山区馨家园学校';
UPDATE ref_middle_school SET district_rank=51 WHERE district_id=10 AND name='上海师范大学附属宝山罗店中学';
UPDATE ref_middle_school SET district_rank=52 WHERE district_id=10 AND name='上海市民办锦秋学校';
UPDATE ref_middle_school SET district_rank=53 WHERE district_id=10 AND name='上海市宝山区罗店第二中学';
UPDATE ref_middle_school SET district_rank=54 WHERE district_id=10 AND name='上海市宝山区吴淞初级中学';
UPDATE ref_middle_school SET district_rank=55 WHERE district_id=10 AND name='上海世外教育附属宝山美兰湖实验学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=56, reputation_score=76 WHERE district_id=10 AND name='上海市行知中学附属宝山实验学校';
UPDATE ref_middle_school SET district_rank=57 WHERE district_id=10 AND name='上海市宝山区陈伯吹罗店实验学校';
UPDATE ref_middle_school SET district_rank=58 WHERE district_id=10 AND name='上海市虎林中学';
UPDATE ref_middle_school SET district_rank=59 WHERE district_id=10 AND name='华东师范大学附属宝山宝杨实验学校';
UPDATE ref_middle_school SET district_rank=60 WHERE district_id=10 AND name='上海市吴淞第二中学';
UPDATE ref_middle_school SET district_rank=61 WHERE district_id=10 AND name='上海市宝山区求真中学南校';
UPDATE ref_middle_school SET district_rank=62 WHERE district_id=10 AND name='上海市月浦中学';
UPDATE ref_middle_school SET district_rank=63 WHERE district_id=10 AND name='上海市盛桥中学';
UPDATE ref_middle_school SET district_rank=64 WHERE district_id=10 AND name='上海市白茅岭学校（上海市白茅岭学校军天湖分校）';
UPDATE ref_middle_school SET tier='三梯队', district_rank=65, reputation_score=58 WHERE district_id=10 AND name='上海市宝山实验学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=66, reputation_score=58 WHERE district_id=10 AND name='上海市顾村中学';
UPDATE ref_middle_school SET district_rank=67 WHERE district_id=10 AND name='上海金瑞学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=11 AND name='上海民办华曜嘉定初级中学';
UPDATE ref_middle_school SET district_rank=2, reputation_score=88 WHERE district_id=11 AND name='交大附中附属嘉定德富中学';
UPDATE ref_middle_school SET district_rank=3, reputation_score=80 WHERE district_id=11 AND name='交大附中附属嘉定洪德中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=11 AND name='上海华旭双语学校';
UPDATE ref_middle_school SET district_rank=5, reputation_score=84 WHERE district_id=11 AND name='中科院上海实验学校';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=11 AND name='上海嘉定区世外学校';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=11 AND name='上海外国语大学嘉定外国语学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=8, reputation_score=76 WHERE district_id=11 AND name='同济大学附属嘉定实验中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=11 AND name='上海市民办远东学校';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=11 AND name='上海市嘉定区练川实验学校';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=11 AND name='上海市民办嘉宜初级中学';
UPDATE ref_middle_school SET district_rank=12, reputation_score=75 WHERE district_id=11 AND name='上海市嘉定区新城实验中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=13, reputation_score=76 WHERE district_id=11 AND name='上海市民办桃李园实验学校';
UPDATE ref_middle_school SET district_rank=14, reputation_score=74 WHERE district_id=11 AND name='上海市曹杨二中附属江桥实验中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=11 AND name='上海市嘉定区黄渡中学';
UPDATE ref_middle_school SET district_rank=16, reputation_score=76 WHERE district_id=11 AND name='同济大学附属实验中学';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=11 AND name='上海市嘉定区朱桥学校';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=11 AND name='上海师范大学附属第五嘉定实验学校';
UPDATE ref_middle_school SET district_rank=19, reputation_score=70 WHERE district_id=11 AND name='上海市嘉定区迎园中学';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=11 AND name='上海市嘉定区南苑中学';
UPDATE ref_middle_school SET district_rank=21, reputation_score=66 WHERE district_id=11 AND name='上海大学附属嘉定留云中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=11 AND name='上海市嘉定区嘉二实验学校';
UPDATE ref_middle_school SET district_rank=23, reputation_score=64 WHERE district_id=11 AND name='上海嘉定区民办华盛怀少学校';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=11 AND name='上海市嘉定区方泰中学';
UPDATE ref_middle_school SET district_rank=25, reputation_score=66 WHERE district_id=11 AND name='上海市嘉定区南翔中学';
UPDATE ref_middle_school SET district_rank=26, reputation_score=60 WHERE district_id=11 AND name='上海市嘉定区苏民学校';
UPDATE ref_middle_school SET district_rank=27, reputation_score=58 WHERE district_id=11 AND name='上海市嘉定区金鹤学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=28, reputation_score=58 WHERE district_id=11 AND name='上海市嘉定区震川中学';
UPDATE ref_middle_school SET district_rank=29 WHERE district_id=11 AND name='上海市嘉定区嘉一实验初级中学';
UPDATE ref_middle_school SET district_rank=30 WHERE district_id=11 AND name='上海市嘉定区华亭学校';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=11 AND name='上海市嘉定区娄塘学校';
UPDATE ref_middle_school SET district_rank=32, reputation_score=56 WHERE district_id=11 AND name='上海市嘉定区丰庄中学';
UPDATE ref_middle_school SET district_rank=33, reputation_score=55 WHERE district_id=11 AND name='上海市嘉定区启良中学';
UPDATE ref_middle_school SET district_rank=34, reputation_score=58 WHERE district_id=11 AND name='上海市嘉定区华江中学';
UPDATE ref_middle_school SET tier='三梯队', district_rank=35, reputation_score=58 WHERE district_id=11 AND name='上海市嘉定区疁城实验学校';
UPDATE ref_middle_school SET district_rank=36 WHERE district_id=11 AND name='上海市嘉定区外冈中学';
UPDATE ref_middle_school SET district_rank=37, reputation_score=45 WHERE district_id=11 AND name='上海市嘉定区戬浜学校';
UPDATE ref_middle_school SET district_rank=38 WHERE district_id=11 AND name='上海市嘉定区马陆育才联合中学';
UPDATE ref_middle_school SET district_rank=39 WHERE district_id=11 AND name='上海市嘉定区徐行中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=14 AND name='上海市松江九峰实验学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=14 AND name='上海市松江区民办茸一中学';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=14 AND name='上海工程技术大学附属松江泗泾实验学校';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=14 AND name='华东政法大学附属松江实验学校';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=14 AND name='上海市松江区第七中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=14 AND name='上海市松江区新闵学校';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=14 AND name='上海市西外外国语学校';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=14 AND name='上海市松江区九亭第二中学（含领科校区）';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=14 AND name='上海外国语大学松江外国语学校';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=14 AND name='上海市松江区九亭中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=14 AND name='上海对外经贸大学附属松江实验学校花园分校';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=14 AND name='上海师范大学附属松江实验学校';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=14 AND name='上海市三新学校松江思贤分校';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=14 AND name='上海市松江区第六中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=14 AND name='上海外国语大学附属外国语学校松江云间中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=14 AND name='上海师范大学松江科创实验学校';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=14 AND name='上海市松江区科技学校';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=14 AND name='上海市三新学校松江东部分校';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=14 AND name='上海市松江一中附属叶榭学校';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=14 AND name='上海市松江区泗泾实验学校';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=14 AND name='上海市松江区新桥中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=14 AND name='上海市松江区洞泾学校';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=14 AND name='上海戏剧学院附属松江实验学校';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=14 AND name='上海政法学院附属松江外国语学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=25, reputation_score=76 WHERE district_id=14 AND name='东华大学附属实验学校';
UPDATE ref_middle_school SET district_rank=26 WHERE district_id=14 AND name='上海市松江区第五中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=27, reputation_score=76 WHERE district_id=14 AND name='上海市松江区民乐学校';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=14 AND name='上海世外教育附属松江区车墩学校';
UPDATE ref_middle_school SET district_rank=29 WHERE district_id=14 AND name='上海市松江区佘山学校';
UPDATE ref_middle_school SET district_rank=30 WHERE district_id=14 AND name='东华大学附属实验学校松江小昆山分校';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=14 AND name='上海市松江区仓桥学校';
UPDATE ref_middle_school SET district_rank=32 WHERE district_id=14 AND name='上海市松江区张泽学校';
UPDATE ref_middle_school SET district_rank=33 WHERE district_id=14 AND name='上海市松江区洞泾外国语实验学校';
UPDATE ref_middle_school SET district_rank=34 WHERE district_id=14 AND name='上海市松江区天马山学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=35, reputation_score=58 WHERE district_id=14 AND name='上海市三新学校';
UPDATE ref_middle_school SET district_rank=36 WHERE district_id=14 AND name='上海师范大学松江未来实验学校';
UPDATE ref_middle_school SET district_rank=37 WHERE district_id=14 AND name='上海赫贤学校';
UPDATE ref_middle_school SET tier='三梯队', district_rank=38, reputation_score=58 WHERE district_id=14 AND name='上海市松江二中附属浦南实验学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=15 AND name='上海青浦兰生学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=15 AND name='上海青浦区世外学校';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=15 AND name='上海市青浦区第一中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=15 AND name='上海市毓秀学校';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=15 AND name='上海市教育学会青浦清河湾中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=15 AND name='上海市青浦区教育学院附属中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=15 AND name='上海市青浦区豫才中学';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=15 AND name='上海市青浦区思源中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=15 AND name='上海市青浦区珠溪中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=15 AND name='上海市青浦区凤溪中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=15 AND name='上海宋庆龄学校';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=15 AND name='上海五浦汇实验学校';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=15 AND name='上海市青浦区徐泾中学';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=15 AND name='上海市青浦区白鹤中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=15 AND name='上海市青浦区第一中学尚美分校';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=15 AND name='上海市博文学校';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=15 AND name='上海市青浦区华新中学';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=15 AND name='上海政法学院附属青浦崧淀中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=15 AND name='上海市青浦区崧泽学校';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=15 AND name='上海师范大学附属青浦实验中学';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=15 AND name='上海师范大学附属青浦重固学校';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=15 AND name='上海市青浦区金泽中学';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=15 AND name='上海青浦区协和双语学校';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=15 AND name='上海市毓华学校';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=15 AND name='上海市佳信学校';
UPDATE ref_middle_school SET district_rank=26 WHERE district_id=15 AND name='上海市青浦区颜安中学';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=15 AND name='上海市青浦区少年业余体育学校';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=15 AND name='上海市青浦区沈巷中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=29, reputation_score=76 WHERE district_id=15 AND name='上海市青浦区实验中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=30, reputation_score=76 WHERE district_id=15 AND name='上海市青浦区东方中学';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=15 AND name='上海青浦平和双语学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=16 AND name='上海市奉贤区实验中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=16 AND name='上海市奉贤区育秀中学';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=16 AND name='上海市奉贤中学附属初级中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=16 AND name='上海外国语大学附属奉贤实验中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=16 AND name='上海市奉贤区待问中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=16 AND name='上海市奉贤区青溪中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=16 AND name='上海市奉贤区星火学校';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=16 AND name='上海市奉贤区钱桥学校';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=16 AND name='上海奉贤区世外学校';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=16 AND name='上海市奉贤区崇实中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=16 AND name='上海市奉贤区汇贤中学';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=16 AND name='上海市奉贤区华亭学校';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=16 AND name='上海市奉贤区西渡学校';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=16 AND name='上海市奉贤区阳光外国语学校';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=16 AND name='上海市奉贤区尚同中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=16 AND name='上海市奉贤区胡桥学校';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=16 AND name='上海市奉贤区奉城第二中学';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=16 AND name='上海市奉贤区古华中学';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=16 AND name='上海市奉贤中学附属南桥中学';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=16 AND name='上海市奉贤区庄行学校';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=16 AND name='上海理工大学附属奉贤学校';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=16 AND name='上海师范大学附属奉贤实验中学';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=16 AND name='上海市奉贤区奉浦中学';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=16 AND name='上海市奉贤区塘外中学';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=16 AND name='上海市奉贤区肖塘中学';
UPDATE ref_middle_school SET district_rank=26 WHERE district_id=16 AND name='上海市奉贤区邬桥学校';
UPDATE ref_middle_school SET district_rank=27 WHERE district_id=16 AND name='上海市奉贤区蓝湾五四学校';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=16 AND name='上海奉贤区世外教育附属临港外国语学校';
UPDATE ref_middle_school SET district_rank=29 WHERE district_id=16 AND name='上海市奉贤区柘林学校';
UPDATE ref_middle_school SET district_rank=30 WHERE district_id=16 AND name='上海市奉贤区洪庙中学';
UPDATE ref_middle_school SET district_rank=31 WHERE district_id=16 AND name='上海市奉贤区肇文学校';
UPDATE ref_middle_school SET district_rank=32 WHERE district_id=16 AND name='上海大学附属奉贤实验学校';
UPDATE ref_middle_school SET district_rank=33 WHERE district_id=16 AND name='上海市奉贤区平安学校';
UPDATE ref_middle_school SET district_rank=34 WHERE district_id=16 AND name='上海市奉贤区齐贤学校';
UPDATE ref_middle_school SET district_rank=35 WHERE district_id=16 AND name='上海市奉贤区新寺学校';
UPDATE ref_middle_school SET district_rank=36 WHERE district_id=16 AND name='上海市奉贤区青村中学';
UPDATE ref_middle_school SET district_rank=37 WHERE district_id=16 AND name='上海市奉贤中学附属三官堂学校';
UPDATE ref_middle_school SET district_rank=38 WHERE district_id=16 AND name='上海市奉贤区头桥中学';
UPDATE ref_middle_school SET district_rank=39 WHERE district_id=16 AND name='上海市奉贤区四团中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=40, reputation_score=76 WHERE district_id=16 AND name='上海市奉贤区弘文学校';
UPDATE ref_middle_school SET district_rank=41 WHERE district_id=16 AND name='上海市奉贤区青少年业余体育学校';
UPDATE ref_middle_school SET district_rank=42 WHERE district_id=16 AND name='上海市奉贤区邵厂学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=13 AND name='上海市蒙山中学';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=13 AND name='上海金山区世外学校';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=13 AND name='上海市新农学校';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=13 AND name='上海金山区健桥实验中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=13 AND name='上海市山阳中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=13 AND name='上海市干巷学校';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=13 AND name='上海师范大学附属金山前京中学';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=13 AND name='上海市金山区教育学院附属中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=13 AND name='上海市同凯中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=13 AND name='上海市朱行中学';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=13 AND name='上海市西林中学';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=13 AND name='上海市民办金盟学校';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=13 AND name='上海市金山实验中学';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=13 AND name='华东师范大学附属枫泾中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=13 AND name='上海市亭新中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=13 AND name='上海市民办永昌中学';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=13 AND name='上海市张堰第二中学';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=13 AND name='上海市金山区青少年业余体育学校';
UPDATE ref_middle_school SET district_rank=19 WHERE district_id=13 AND name='上海市金卫中学';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=13 AND name='上海市金山区龙泉学校';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=13 AND name='上海市漕泾中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=13 AND name='上海市松隐中学';
UPDATE ref_middle_school SET district_rank=23 WHERE district_id=13 AND name='上海市金山区吕巷学校';
UPDATE ref_middle_school SET district_rank=24 WHERE district_id=13 AND name='上海市廊下中学';
UPDATE ref_middle_school SET district_rank=25 WHERE district_id=13 AND name='上海市金山区钱圩学校';
UPDATE ref_middle_school SET tier='二梯队', district_rank=26, reputation_score=76 WHERE district_id=13 AND name='上海市金山初级中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=27, reputation_score=76 WHERE district_id=13 AND name='上海市罗星中学';
UPDATE ref_middle_school SET district_rank=28 WHERE district_id=13 AND name='上海金山杭州湾双语学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=1, reputation_score=92 WHERE district_id=17 AND name='上海市实验学校附属东滩学校';
UPDATE ref_middle_school SET tier='一梯队', district_rank=2, reputation_score=92 WHERE district_id=17 AND name='上海市崇明区实验中学';
UPDATE ref_middle_school SET district_rank=3 WHERE district_id=17 AND name='上海市向明初级中学附属崇明区江帆中学';
UPDATE ref_middle_school SET district_rank=4 WHERE district_id=17 AND name='上海市崇明中学附属东门中学';
UPDATE ref_middle_school SET district_rank=5 WHERE district_id=17 AND name='上海市崇明区长明中学';
UPDATE ref_middle_school SET district_rank=6 WHERE district_id=17 AND name='上海市崇明区合兴中学';
UPDATE ref_middle_school SET district_rank=7 WHERE district_id=17 AND name='上海市崇明区长兴中学';
UPDATE ref_middle_school SET district_rank=8 WHERE district_id=17 AND name='上海师范大学附属崇明正大中学';
UPDATE ref_middle_school SET district_rank=9 WHERE district_id=17 AND name='上海市崇明区向化中学';
UPDATE ref_middle_school SET district_rank=10 WHERE district_id=17 AND name='上海市崇明区庙镇学校';
UPDATE ref_middle_school SET district_rank=11 WHERE district_id=17 AND name='上海市崇明区长江学校';
UPDATE ref_middle_school SET district_rank=12 WHERE district_id=17 AND name='上海市崇明区裕安中学';
UPDATE ref_middle_school SET district_rank=13 WHERE district_id=17 AND name='上海新纪元双语学校';
UPDATE ref_middle_school SET district_rank=14 WHERE district_id=17 AND name='上海市崇明区崇东中学';
UPDATE ref_middle_school SET district_rank=15 WHERE district_id=17 AND name='上海市崇明区三烈中学';
UPDATE ref_middle_school SET district_rank=16 WHERE district_id=17 AND name='上海市崇明区大公中学';
UPDATE ref_middle_school SET district_rank=17 WHERE district_id=17 AND name='上海市崇明区大新中学';
UPDATE ref_middle_school SET district_rank=18 WHERE district_id=17 AND name='上海市崇明区建设中学';
UPDATE ref_middle_school SET tier='二梯队', district_rank=19, reputation_score=76 WHERE district_id=17 AND name='上海民办民一中学';
UPDATE ref_middle_school SET district_rank=20 WHERE district_id=17 AND name='上海市崇明区新海学校';
UPDATE ref_middle_school SET district_rank=21 WHERE district_id=17 AND name='上海市崇明区三星中学';
UPDATE ref_middle_school SET district_rank=22 WHERE district_id=17 AND name='上海市崇明区横沙中学';

COMMIT;
