#!/usr/bin/env python3
"""
ETL script to process 名额分配到校 (quota allocation to school) data
and generate SQL seed files.

Usage:
    python scripts/etl_quota_allocation_school.py
"""

import csv
import os
from pathlib import Path
from collections import defaultdict

# District code mapping
DISTRICT_CODES = {
    '黄浦区': 'HP',
    '徐汇区': 'XH',
    '长宁区': 'CN',
    '静安区': 'JA',
    '普陀区': 'PT',
    '虹口区': 'HK',
    '杨浦区': 'YP',
    '闵行区': 'MH',
    '宝山区': 'BS',
    '嘉定区': 'JD',
    '浦东新区': 'PD',
    '浦东区': 'PD',
    '金山区': 'JS',
    '松江区': 'SJ',
    '青浦区': 'QP',
    '奉贤区': 'FX',
    '崇明区': 'CM',
}

def extract_district_name(filename: str) -> str:
    """Extract district name from filename."""
    for district in DISTRICT_CODES.keys():
        if district in filename:
            return district
    return None

def parse_raw_csv(filepath: Path) -> list:
    """Parse raw quota allocation to school CSV file."""
    records = []

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    lines = content.strip().split('\n')
    if len(lines) < 4:
        return records

    # Parse header lines to get high school codes and names
    # Format: first 2 columns are middle school info, then high school columns
    reader = csv.reader(content.split('\n'))

    rows = list(reader)
    if len(rows) < 4:
        return records

    # Find the row with high school codes (6-digit numbers)
    high_school_codes = []
    high_school_names = []

    for row_idx, row in enumerate(rows):
        if not row:
            continue
        # Check if this row contains 6-digit codes
        for i, cell in enumerate(row[2:], start=2):
            cell = cell.strip().strip('"')
            if cell and len(cell) == 6 and cell.isdigit():
                if i >= len(high_school_codes):
                    high_school_codes.extend([''] * (i - len(high_school_codes) + 1))
                high_school_codes[i] = cell

    # Find the row with high school names
    for row_idx, row in enumerate(rows):
        if not row:
            continue
        found_names = False
        for i, cell in enumerate(row[2:], start=2):
            cell = cell.strip().strip('"')
            if cell and '中学' in cell or '附属' in cell:
                found_names = True
                while i >= len(high_school_names):
                    high_school_names.append('')
                high_school_names[i] = cell
        if found_names:
            break

    # Find data rows (start with 6-digit middle school code)
    for row in rows:
        if not row or len(row) < 3:
            continue

        middle_code = row[0].strip().strip('"')
        middle_name = row[1].strip().strip('"') if len(row) > 1 else ''

        # Check if first column is a 6-digit middle school code
        if middle_code and len(middle_code) == 6 and middle_code.isdigit():
            # Extract quota data
            for i in range(2, len(row)):
                if i < len(row):
                    quota_str = row[i].strip().strip('"')
                    if quota_str and quota_str.isdigit():
                        quota_count = int(quota_str)
                        if quota_count > 0 and i < len(high_school_codes) and high_school_codes[i]:
                            records.append({
                                'middle_school_code': middle_code,
                                'middle_school_name': middle_name,
                                'high_school_code': high_school_codes[i],
                                'high_school_name': high_school_names[i] if i < len(high_school_names) else '',
                                'quota_count': quota_count,
                            })

    return records

def generate_sql_seed(records: list, year: int, output_path: Path):
    """Generate SQL seed file for quota allocation to school data."""

    # Group records by district
    by_district = defaultdict(list)
    for rec in records:
        by_district[rec['district_code']].append(rec)

    sql_lines = [
        f"-- =============================================================================",
        f"-- {year}年名额分配到校招生计划",
        f"-- Generated by etl_quota_allocation_school.py",
        f"-- Total Records: {len(records)} across {len(by_district)} districts",
        f"-- =============================================================================",
        "",
        f"-- Delete existing {year} data",
        f"DELETE FROM ref_quota_allocation_school WHERE year = {year};",
        "",
    ]

    for district_code, district_records in sorted(by_district.items()):
        sql_lines.append(f"-- {district_code}: {len(district_records)} records")

        for rec in district_records:
            # Use middle_school_name for lookup since codes might not match
            middle_name_escaped = rec['middle_school_name'].replace("'", "''")
            sql = f"""INSERT INTO ref_quota_allocation_school (year, district_id, high_school_id, high_school_code, middle_school_id, middle_school_name, quota_count, data_year, created_at, updated_at)
SELECT {year}, (SELECT id FROM ref_district WHERE code = '{district_code}'), (SELECT id FROM ref_school WHERE code = '{rec['high_school_code']}' AND data_year = {year}), '{rec['high_school_code']}', (SELECT id FROM ref_middle_school WHERE name = '{middle_name_escaped}' AND district_id = (SELECT id FROM ref_district WHERE code = '{district_code}') LIMIT 1), '{middle_name_escaped}', {rec['quota_count']}, {year}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE EXISTS (SELECT 1 FROM ref_district WHERE code = '{district_code}')
AND EXISTS (SELECT 1 FROM ref_school WHERE code = '{rec['high_school_code']}' AND data_year = {year})
ON CONFLICT (year, high_school_code, middle_school_name) DO UPDATE SET quota_count = EXCLUDED.quota_count, updated_at = CURRENT_TIMESTAMP;"""
            sql_lines.append(sql)
        sql_lines.append("")

    sql_lines.append("")
    sql_lines.append(f"-- Verify: SELECT year, d.code, COUNT(*) FROM ref_quota_allocation_school q JOIN ref_district d ON q.district_id = d.id WHERE year = {year} GROUP BY year, d.code;")
    sql_lines.append("")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))

    print(f"Generated: {output_path} ({len(records)} records)")

def main():
    base_path = Path(__file__).parent.parent
    raw_data_path = base_path / 'original_data' / 'raw'
    seeds_path = base_path / 'db' / 'seeds'

    # Process 2024 data
    print("\n=== Processing 2024 data ===")
    raw_2024_path = raw_data_path / '2024' / 'quota_school'
    all_records_2024 = []

    if raw_2024_path.exists():
        for csv_file in raw_2024_path.glob('*.csv'):
            district_name = extract_district_name(csv_file.name)
            if not district_name:
                print(f"  Skipping {csv_file.name} - district not detected")
                continue

            district_code = DISTRICT_CODES.get(district_name)
            if not district_code:
                print(f"  Skipping {csv_file.name} - unknown district: {district_name}")
                continue

            print(f"  Processing {csv_file.name} -> {district_code}")
            records = parse_raw_csv(csv_file)
            # Add district_code to each record
            for rec in records:
                rec['district_code'] = district_code
            print(f"    Found {len(records)} records")
            all_records_2024.extend(records)

    # Generate combined 2024 seed file
    if all_records_2024:
        output_file = seeds_path / '034_seed_quota_allocation_school_2024_fixed.sql'
        generate_sql_seed(all_records_2024, 2024, output_file)

    # Process 2025 markdown data
    print("\n=== Processing 2025 data ===")
    raw_2025_path = raw_data_path / '2025' / 'quota_district' / 'markdown'
    all_records_2025 = []

    if raw_2025_path.exists():
        for md_file in raw_2025_path.glob('*.md'):
            if md_file.stat().st_size < 100:  # Skip empty or very small files
                continue

            district_name = extract_district_name(md_file.name)
            if not district_name:
                print(f"  Skipping {md_file.name} - district not detected")
                continue

            district_code = DISTRICT_CODES.get(district_name)
            if not district_code:
                print(f"  Skipping {md_file.name} - unknown district: {district_name}")
                continue

            print(f"  Processing {md_file.name} -> {district_code}")

            # Read markdown and extract table data
            with open(md_file, 'r', encoding='utf-8') as f:
                content = f.read()

            # Parse the markdown table - this is tricky because the format varies
            # The content looks like a copy-paste from a spreadsheet
            records = parse_markdown_table(content, district_code)
            # Add district_code to each record
            for rec in records:
                rec['district_code'] = district_code
            print(f"    Found {len(records)} records")
            all_records_2025.extend(records)

    # Generate 2025 seed file
    if all_records_2025:
        output_file = seeds_path / '035_seed_quota_allocation_school_2025_fixed.sql'
        generate_sql_seed(all_records_2025, 2025, output_file)

    print("\n=== Summary ===")
    print(f"2024: {len(all_records_2024)} records")
    print(f"2025: {len(all_records_2025)} records")

def parse_markdown_table(content: str, district_code: str) -> list:
    """Parse markdown content to extract quota allocation data."""
    records = []

    # The markdown content appears to be a copy-paste from Excel
    # It has header rows followed by data rows
    # Format: middle_school_code + middle_school_name + quota columns

    lines = content.strip().split('\n')
    if len(lines) < 3:
        return records

    # Find high school codes from first few lines
    high_school_codes = []
    for line in lines[:5]:
        # Look for 6-digit codes
        parts = line.split()
        for part in parts:
            part = part.strip()
            if len(part) == 6 and part.isdigit():
                high_school_codes.append(part)

    if not high_school_codes:
        return records

    # Find data rows - they start with 6-digit middle school code followed by name
    for line in lines:
        parts = line.split()
        if not parts:
            continue

        # Check if first part is a middle school code (6 digits starting with district code pattern)
        first = parts[0].strip()
        if not (len(first) == 6 and first.isdigit()):
            continue

        middle_code = first

        # Extract middle school name (next few parts until we hit a number)
        name_parts = []
        quota_values = []
        for part in parts[1:]:
            if part.isdigit() and len(part) <= 3:  # quota count is small number
                quota_values.append(int(part))
            else:
                if not quota_values:  # Still in name section
                    name_parts.append(part)

        middle_name = ' '.join(name_parts)

        # Match quota values with high school codes
        for i, quota in enumerate(quota_values):
            if quota > 0 and i < len(high_school_codes):
                records.append({
                    'middle_school_code': middle_code,
                    'middle_school_name': middle_name,
                    'high_school_code': high_school_codes[i],
                    'high_school_name': '',
                    'quota_count': quota,
                })

    return records

if __name__ == '__main__':
    main()
